languages_mapping:
  two_letters_code:
    zh-CN: zh-CN
    zh-TW: zh-TW
preserve_hierarchy: 1
files:
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  # JSON translation files
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
