preserve_hierarchy: true
languages_mapping: &languages_mapping
  two_letters_code:
    zh-CN: zh-CN
    zh-TW: zh-TW
files:
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
    languages_mapping: *languages_mapping
